version: '3.7'

services:
  web:
    build:
      context: ./app/
      dockerfile: Dockerfile.prod
    command: gunicorn site_engine.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - store_volume:/home/app/web/store
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: on-failure
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - store_volume:/home/app/web/store
    ports:
      - 8080:80
    depends_on:
      - web
    restart: on-failure

volumes:
  postgres_data:
  static_volume:
  store_volume: