version: '3.7'

services:
  web:
    build: app/
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dw_django
      - POSTGRES_PASSWORD=dw_django
      - POSTGRES_DB=dw_django_dev

volumes:
  postgres_data: